name: EKS Kubectl Ops - Dev

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  kubectl-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_DEV }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name dev-cluster

      - name: Run kubectl commands
        run: |
          kubectl get pods -A
          kubectl get secrets -A
